FROM golang:1.22 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o ./build/main ./cmd/

ENV ENV=dev

ENV START_TIMEOUT=10s
ENV SHUTDOWN_TIMEOUT=10s

ENV HTTP_ADDRESS=localhost:9090
ENV HTTP_TIMEOUT=20s
ENV HTTP_IDLE_TIMEOUT=4s

ENV GRPC_PORT=44050
ENV GRPC_TIMEOUT=10s

ENV MONGODB_URI="mongodb://username:password@host:port"
ENV MONGODB_PING_TIMEOUT="10s"
ENV MONGODB_DATABASE_NAME="database"

ENV USER_SERVICE_ADDRESS=localhost:44044
ENV USER_SERVICE_TIMEOUT=10s
ENV USER_SERVICE_RETRIES_COUNT=2

ENV JWT_SECRET="secret"


EXPOSE 9090
EXPOSE 44050

ENTRYPOINT ["./build/main"]